# Generated by Django 5.1.11 on 2025-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("preview", models.ImageField(upload_to="images/blog/%Y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=False)),
                ("views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Пост",
                "ordering": ["created_at"],
            },
        ),
    ]
