# Generated by Django 5.2.1 on 2025-06-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="photos/", verbose_name="Фотография"
            ),
        ),
    ]
