# Generated by Django 5.2.1 on 2025-07-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20250728_1229"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewModel",
        ),
    ]
