# Generated by Django 5.2.1 on 2025-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_posts_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                default="<PIL.Image.Image image mode=RGB size=300x200 at 0x2060A1F7ED0>",
                null=True,
                upload_to="photos/",
                verbose_name="Фотография",
            ),
        ),
    ]
