# Generated by Django 5.2.1 on 2025-06-11 08:57

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_posts_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="preview",
            field=models.ImageField(
                null=True,
                upload_to=pathlib.PureWindowsPath(
                    "C:/Users/Maxim-NOTE/Documents/Skypro/22_Django/media"
                ),
                verbose_name="Фотография",
            ),
        ),
    ]
