# Generated by Django 5.2.1 on 2025-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_posts_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="number_views",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Количество просмотров",
                verbose_name="Количество просмотров",
            ),
        ),
    ]
