# Generated by Django 5.2.1 on 2025-07-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Укажите модель", max_length=100, verbose_name="Наименование"
            ),
        ),
    ]
